// ==============================
// DATABASE CONFIGURATION
// ==============================

// Import Sequelize, a modern ORM (Object-Relational Mapper) for Node.js.
// It allows us to interact with the database using JavaScript objects instead of raw SQL.
const { Sequelize } = require('sequelize');

// Import 'path' module to handle file paths correctly across different OS (Windows/Mac/Linux).
const path = require('path');

// Initialize a new Sequelize instance.
// This sets up the connection to our SQLite database.
const sequelize = new Sequelize({
    dialect: 'sqlite', // Specifies we are using SQLite (a file-based database)

    // The path to the database file.
    // __dirname is the current folder (backend/config).
    // '../database.sqlite' moves up one level to 'backend/database.sqlite'.
    storage: path.join(__dirname, '../database.sqlite'),

    // Logging option:
    // set to console.log to see the raw SQL queries generated by Sequelize.
    // We set it to false to keep the console clean during production/demo.
    logging: false
});

// Export the configured instance so it can be used in other files (like models/server.js).
module.exports = sequelize;